### ISSUE TITLE
Support eStat Chochomoku polygon base reverse geocode

### ISSUE THREAD

**Issue by sanak** [gtt-project/pgGeocoder#2]
I noticed that if reverse geocode doesn't find nearest X m records from `addresses` table which represents Gaiku level address information, it returns empty as result.
https://github.com/bizyman/pgGeocoder/blob/places/sql/pgReverseGeocoder.sql#L89-L98

But I think that reverse geocode should return result when it is in Japan.

Not to break API arugments, I think that importing eStat Chochomoku (Chome) polygon data is meaningful, but how about this ?
(In the following QGIS screenshot, black border boundaries come from eStat 2015 Shochiiki data, and red points come from national census Gaiku and blue points come from national census Oaza data.
<img width="1194" alt="pgGeocoder_wakayama" src="https://user-images.githubusercontent.com/629923/74630679-73efcf00-519e-11ea-8d23-de51aa3540b2.png">

**Comment by dkastl** [comment]
Maybe a "max. search radius" could be an optional argument? 
Because sometimes it may be a valid result to have no nearest address point in a certain distance.

Alternatively the distance to the reverse geocoded point could be returned and it's then up to the user to accept it or not.

Nevertheless, a maximum search radius is good for performance, because it allows to limit the search BBOX, so I would prefer the optional argument with a default value.

**Comment by sanak** [comment]
@dkastl @mbasa (CC: @aruneko, @50-LeoWatanabe)   
> Maybe a "max. search radius" could be an optional argument?

Well, the radius is available already, but when I tried to use larger radius, the response became quite bad.
https://github.com/gtt-project/pgGeocoder/blob/places/sql/pgReverseGeocoder.sql#L72

Also, we noticed that there seems to be problem when reverse geocoding at near by admin boundary, so it seems to be better to switch admin boundary search first approach about this.

I will prepare to design the search algorithm flow in next week, once, so please wait for a while.

**Comment by sanak** [comment]
This is already supported, so I close this.
